import { Inter } from "next/font/google";
import { Button } from "@windmill/react-ui";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TOSOM Insights : Test Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Button>Click Me</Button>
        {children}
      </body>
    </html>
  );
}
